version: "3"

services:
    opc-ua-server:
        build: ./OPC-UA-server
        environment:
            OPC_UA_SERVER_PORT: 4840
            NAMESPACE_URI: http://plant_simulation

    opc-ua-client:
        build: ./OPC-UA-client
        restart: on-failure
        environment:
            IN_DOCKER: 1
            OPC_UA_SERVER_URL: opc.tcp://opc-ua-server:4840
            NAMESPACE_URI: http://plant_simulation
            KAFKA_BROKER_URL: broker:9092
            KAFKA_TOPIC: production.cycles

networks:
    default:
        external:
            name: OPC-UA